package threads;

public class ResultTask extends Thread{
    public void run(){
        System.out.println("result generated by:"+Thread.currentThread().getName());
    }
    public static void main(String[] args) {
        ResultTask t1=new ResultTask();
        t1.run();//normal excetution -> always the main thread
        t1.start(); //multi threading -> thread 0,thread 1,t3...
        //start() internaly calls run()
    }
}
